format = """
${custom.mac_user}\
${custom.mac_model}\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$line_break\
$status\
$character"""

[character]
success_symbol = "[􀆔](bold fg:#CDCED0) "
error_symbol = "[􀆔](bold fg:#EC3D50) "


[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1
format = "[$read_only]($read_only_style)[$path]($style) "
style = "bold fg:blue"
read_only = "􀎡 "
read_only_style = "fg:#F69F37"
truncation_symbol = "…/"

[git_branch]
symbol = "\uf418 "
style = "bold fg:#F05032"

[git_commit]
tag_symbol = "\uf02b "
tag_disabled = false

[git_status]
stashed = "\uf487"
style = "bold fg:yellow"

[python]
symbol = "\ue73c "
style = "bold fg:#3776AB"

[custom.mac_user]
description = "Show the shortname of the user"
command = "id -F | awk '{print $1}'"
style = "bold fg:#F6C05E"
format = "[$output]($style) on "
when = true

[custom.mac_model]
description = "Show the model of the Mac"
command = "/usr/local/sbin/starship-mac-model"
os = "macos"
style = "bold fg:#CDCED0"
format = "[$output]($style) in "
when = true
